[tool.poetry]
name = "textnet"
version = "0.1.0"
description = ""
authors = ["c4y <c4y@c4yg70.fun>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymoo = "^0.6.0.1"
evoxbench = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
